#+TITLE: Notes
Abstract: Udpensl delen om forventningen til projektet. Hvad er den korte version om alt hvad vi har lavet (forklar det til en hypotetisk Fritz) Background - husk weakest precondition vs wlp vs strongest postcondition Designvalg - fx method 1 vs method 2 Spekulationer om udvidelse til PER - er det nemt at udvidde det vi har skrevet Concurrency? Et nondeterministisk valg mellem s1 og s2? At tænke over hvor nemt det er at udvidde er en måde at lave en evaluering ar vores arbejde

Skal vi skrive noget contribution? Så skal vi have nogle overvejelser at basere det på


OK Så det mærkeligt at vi bruger INTEGER og ikke INT, det er nice at man kan udregne store ting, men gør bruteforcing quantifers umuligt og i guess varianten stadig giver mening men kommer til at tage unreasonably lang tid.

Burde vi tænke over run-time assertions? Der står i de der slides at run-time assertions kan introduce run-time failures, og at verification skal garantere absence of run-time failures (slide 26).

Måske quickcheck af aexpr og bexpr

TODO:
