name:                IFC
version:             0.1.0.0
github:              "Spatenheinz/IFC"
license:             BSD3
author:              "Jacob herbst"
maintainer:          "jacob@1362.dk"
copyright:           "2022 Jacob herbst"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Spatenheinz/IFC#readme>

dependencies:
- base >= 4.7 && < 5
- parser-combinators >= 1.3.0
- megaparsec >= 9.2.0 && < 10
- mtl
- containers
- sbv >= 8.15

ghc-options:
- -Wall
# - -Werror
- -Wdefault
- -fwarn-tabs

library:
  source-dirs: src
  # exposed-modules:
  #   - AST
  #   - Eval
  #   - Parser

executables:
  IFC-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - IFC

tests:
  IFC-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - IFC
    - tasty
    - tasty-hunit
    - QuickCheck
    - tasty-quickcheck
